# Data Structure

<h2>Assignment 1: Differences between Data Structure</h2>

Answer this question:

Explain the differences between List, Tuple, Set dan Dictionary!

List
- the type of the contained data can be anything
- the contained data can have different types
- the contained data can be changed
- Notated as " List = [a,b,c,...] "

Tuple
- Doesn't support partial change
- Notated as " Tuple = (a,b,c,..) "

Set
- Doesn't have index
- Can't have more than one element that contains a same value
- Notated as " Set = {a,b,c,...} "

Dictionary
- Doesn't have index (order-strict)
- Contains keys and values
- Notated as " Dictionary = {'A':'a','B':'b',...} "



---



---



# List

<h2>Assignment 2: List Access</h2>

Complete the code below to obtain the expected output !

In [ ]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list


In [ ]:
a[1:5]

['13b', 'aa1', 1.32, 22.1]

Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]



---



<h2>Assignment 3: Nested List Access</h2>

Complete the code below to obtain the expected output !

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list


In [ ]:
a[1][1:3]

[0, 6]

Expected Output :


[0, 6]



---



<h2>Assignment 4: List Manipulation</h2>

Complete the code below to obtain the expected output !

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value

print(a)

[[5, 9, 8], [0, 0, 6]]


In [ ]:
a[0][2] = 10
a[1][0] = 11

print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]



---



<h2>Assignment 5: Delete Element List</h2>

Complete the code below to produce the expected output

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Remove the elements that have value "bathroom" & 10.50 in only one codeline

del(areas[8:10])

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]





---



## Assignment 6: List Comprehension

Use the **List Comprehension** method to search the element of S that equal to zero when divided by 2. Then, assign the result in form of a list into variable T.

In [ ]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [i for i in S if i%2==0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]



---



---



# Tuple

## Assignment 7. Accesing Tuple

Use the Slicing to access the tuple below, so it can produced the expected output

In [ ]:
tuple_1 = (1, 2, 6, 7, 8, 9, 10)

#akses tuple


In [ ]:
print(tuple_1[2:5])

(6, 7, 8)


Expected Outpout:


(6, 7, 8)



---



---



# Dictionary

<h2>Soal 8: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# Add a key "italy" with "rome" as its value into the dictionary
# Check if "italy" is avaiable in the dictionary

europe.update({'italy':"rome"})
#Checking
"italy" in europe


True

Expected Output:
    
True



---



<h2>Asignment 9: Update dan Remove Dictionary</h2>
    
Complete the code below to produce the expected output

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# Update the capital of germany into berlin
europe['germany'] = "berlin"

# remove australia dari europa
del europe['australia']

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}



---



<h2>Asignment 10: Nested Dictionary</h2>
    
Complete the code below to produce the expected output

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country['indonesia'] = {'capital':'jakarta','population':250}

print(country)


80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}



---



<h2>Assignment 11: Loop Dictionary</h2>
    
Complete the code below to produce the expected output

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for key, value in country.items():
    print('Ibukota '+ str(key) +' adalah ' + str(value['capital']))

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta



---



---



# Set

## Assignment 12: Remove Duplicate using set

Remove the duplicated value form the list using the set method. The final type of variable should be a "set"


In [ ]:
obj_list = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 9, 10]

#using set
obj_list = set(obj_list)
print(obj_list)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}


Expected output: 

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}



---



## Assignment 13: Changing or deleting the element of set

Change and delete the element of the set to produce the expected output



In [ ]:
set_1 = {1, 2, 3, 4, 5}

# Add the element of the set with valur {6,7,8}
set_1.update([6,7,8])

#hapus nilai anggota set 8
set_1.discard(8)

print(set_1)

{1, 2, 3, 4, 5, 6, 7}


Expected output:

{1, 2, 3, 4, 5, 6, 7}



---



## Asignment 14: Set Operation

Obtain the intersection between these two sets

In [ ]:
set_2 = {6, 8, 9, 10, 24}
set_3 = {6, 10, 8, 25, 13}

#intersection set
#method 1
print(set_2 & set_3)

#method 2
print(set_2.intersection(set_3))

{8, 10, 6}
{8, 10, 6}


Expected output:


{6, 8, 10}



---



---

