# List

<h2>Soal 1: Sifat List</h2>

Jawab Pertanyaan di bawah ini:

Jenis data apa saja yang bisa ada di dalam List?

JAWAB :

1. Integer

2. Float

3. Double

4. String

5. Boolean, dsb.

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
# Menggunakan "list[start,stop]"
# List akan diakses mulai dari "start" dan akan berhenti sebelum "stop" (index dimulai dari 0) 
a[1:5]

['13b', 'aa1', 1.32, 22.1]

Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [1.32, 22.1, 2.34]
b = ['1', '13b', 'aa1']
c = [3, 40, 100]
# combine list
# Nested List dibentuk dengan membuat sebuah list yang diisi dengan beberapa sub-list, yang dipisahkan dengan tanda koma
[a,c,b]

[[1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1']]

Expected Output :

[ [1.32, 22.1, 2.34], [3, 40, 100], ['1', '13b', 'aa1'] ]

<h2>Soal 4: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
# Nested List diakses dengan menggunakan "list[*sequence list*][*sequence sublist*]
a[1][1:3]


[0, 6]

Expected Output :


[0, 6]

<h2>Soal 5: Built in Function List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
p = [0, 5, 2, 10, 4, 9]
# ordered list
# Menggunakan "sorted(iterable, reverse=*boolean*)
# iterable merupakan list, sedangkan reverse akan mengurutkan dari terbesar apabila bernilai "true", dan sebaliknya.
print(sorted(p, reverse=False))
# get max value of list
# Menggunakan "max(iterable)"
print(max(p))

[0, 2, 4, 5, 9, 10]
10


Expected Output :

[0, 2, 4, 5, 9, 10]

10

<h2>Soal 6: List Operation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [1, 3, 5]
b = [5, 1, 3]
# combine list
# Menggabungkan beberapa list, dapat dilakukan dengan menggunakan operator tambah (+)
b+a

[5, 1, 3, 1, 3, 5]

Expected Output :

[5, 1, 3, 1, 3, 5]

<h2>Soal 7: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# Mengganti list value dilakukan dengan mendefenisikan nilai baru untuk list yang bersangkutan sesuai dengan indexnya
# change list value
a[0][2] = 10 
# change list value
a[1][0] = 11
print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 8: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code

# Untuk permasalahan ini, elemen list dihapus menggunakan "del list[*start*:*stop*]" 
del areas[8:10]
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 9: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [ ]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [] # Mendeklarasikan variabel "T" sebagai empty list
for i in S :
  if i % 2 == 0 :
    T.append(i)   # Menggunakan method "list.append(element)". Dengan element-nya adalah variabel "i".
                  # i yang memenuhi syarat (habis dibagi 2), akan dimasukkan ke list "T" (akhir dari list).
print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]

# Dictionary

<h2>Soal 10: Akses Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# print semua key yang ada di objek europe
# Menggunakan method "dictionary.keys()"
print(europe.keys()) 
# print nilai dari key franche
# Menggunakan "dictionary[key]"
print(europe['france'])

dict_keys(['spain', 'france', 'germany', 'norway'])
paris


Expected Output:

dict_keys(['spain', 'france', 'germany', 'norway'])

paris

<h2>Soal 11: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma

# Menggunakan " dictionary [*new_key*] = *new value* "
europe["itali"] = "roma"

# cek apakah itali ada di dalam objek dictionary

def keyCheck(key): # definisi fungsi untuk mengecek ketersediaan key"
  if key in europe :
    return True
  else :
    return False
 
print(keyCheck('itali')) # Pemanggilan fungsi keyCheck

True


Expected Output:
    
True

<h2>Soal 12: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin

# Menggunakan method "dictionary.update({key:value})"
# Update dapat dilakukan dengan cara memilih target *key* dan memasukkan *value* yang baru, dan sebaliknya.
# Apabila key dan value, masing-masing merupakan item yang baru, maka akan menambahkan entry baru pada dictionary

europe.update({'germany': 'berlin'})

# remove australia dari europa

# Menggunakan "del dictionary[key]"
del europe['australia']

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 13: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?

# Menggunakan "dictionary[key][sub-key]"
print(country['germany']['population'])

# update data baru, yaitu negara indonesia dengan capital jakarta dan populasi 250

# Menggunakan "dictionary[key] = { sub-item_1, ..., sub-item_n}
country["indonesia"] = { 'capital':'jakarta', 'population':250 }
print(country)

80.62
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 14: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [ ]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for negara, ibuKota in country.items(): # variabel "negara" akan mengakses key dan varibel "ibuKota" akan mengakses value dari list "country"
    print(' Ibukota ' + negara + ' adalah ' + ibuKota.get("capital")) # dictonary.get(key) akan mengakses value dari key yang spesifik

 Ibukota spain adalah madrid
 Ibukota france adalah paris
 Ibukota germany adalah berlin
 Ibukota norway adalah oslo
 Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta

<h2>Tugas Tambahan 1 : Remove Duplicate List</h2>

In [ ]:
# solusi tanpa menggunakan set
def remove_duplicate(obj_list):
    new_list = [] #deklarasi empty list
    for i in obj_list :
      if i not in new_list : # Jika i tidak terdapat pada new_list, maka akan ditambahkan ke dalam new_list. Sebaliknya, iterasi langsung dilanjutkan.
          new_list.append(i)
    return new_list

# solusi dengan menggunakan set
def remove_duplicate_with_set(obj_list):  
    new_list = list(set(obj_list)) # Mengkonversi obj_list kedalam tipe set akan menghapus seluruh duplikasi dari list tersebut.
                                   # Untuk menghasilkan new_list, set tersebut dikonversikan lagi kedalam tipe list.
    return new_list

obj_list = [1, 2, 4, 6, 2, 1, 4, 5, 7, 8, 6]
print(remove_duplicate(obj_list))
print(remove_duplicate_with_set(obj_list))


# output :
# [1, 2, 4, 6, 5, 7, 8]
# [1, 2, 4, 5, 6, 7, 8]



[1, 2, 4, 6, 5, 7, 8]
[1, 2, 4, 5, 6, 7, 8]


<h2>Tugas Tambahan 2 : Membuat ChatBot Sederhana</h2>

In [ ]:
# import library
from datetime import datetime
import random

# ganti dengan sebuah nama
nama  = "GLaDOS"
# variabel tanggal
tanggal = datetime.now().day
# default variabel untuk pertanyaan tidak diketahui
default = "maaf, aku tidak tahu jawaban dari pertanyaanmu"

# Membuat objek dictionary berisi berbagai opsi jawaban

# list jawaban untuk pertanyaan tentang nama
jawaban_nama = [
      "nama saya  {0}".format(nama),
      "orang-orang memanggil saya {0}".format(nama),
      "panggil saja saya {0}".format(nama)
   ]

# list jawaban untuk pertanyaan tentang tanggal
jawaban_tanggal = [
      "hari ini tanggal {0}".format(tanggal),
      "ya ampun masa tidak tahu, hari ini tanggal {0}".format(tanggal)
    ]

# opsi pertanyaan yang bisa dijawab
pertanyaan = {
  "nama kamu siapa?": jawaban_nama,
  "kamu siapa?" : jawaban_nama,
  "tanggal berapa hari ini?": jawaban_tanggal,
  "hari ini tanggal berapa?" : jawaban_tanggal,
  "default": default
}

# list jawaban untuk sebuah argument selain pertanyaan
statement =  [
                  'ceritakan lebih banyak!',
                  'kenapa kamu berpikir begitu?',
                  'sudah berapa lama kamu merasa seperti ini?',
                  'Itu sangat menarik!',
                  'oh wow!',
                  ':)'
              ]

# respon keseluruhan
responses = {
    'pertanyaan' : pertanyaan,
    'statement' : statement
}
#------
             
# ayo buat chatbotmu
def chatbot(message):
    ## code disini
    if message.find('?') != -1 : # Mendeteksi apabila variabel message merupakan pertanyaan, dengan memeriksa ketersidaan tanda tanya diakhir string
                                 # Jika ada, akan menghasilkan nilai sesuai dengan posisi tanda tanya. Sebaliknya, akan menghasilkan nilai -1. 

      if message in pertanyaan : # Jika message merupakan key yang terdapat pada dictionary pertanyaan, 
                                 # maka meng-return value dari list yang bersangkutan, dari dictionary 'pertanyaan'secara random
        return random.choice(responses['pertanyaan'][message])
      elif message not in pertanyaan: # Jika message merupakan key yang tidak terdapat pada dictionary pertanyaan, 
                                      # maka meng-return value dari key 'default', dari dictionary 'pertanyaan'
        return responses['pertanyaan']['default']
    else :                                          # Jika variabel message tidak memiliki tanda tanya,
                                                    # maka meng-return value dari list 'statement' secara random
      return random.choice(responses['statement'])


print(chatbot('Selamat Pagi'))
print(chatbot('Mau bermain bersamaku?'))
print(chatbot('nama kamu siapa?'))
print(chatbot('hari ini tanggal berapa?'))

# output :
# :)
# maaf, aku tidak tahu jawaban dari pertanyaanmu
# orang-orang memanggil saya Nama Anda
# ya ampun masa tidak tahu, hari ini tanggal

:)
maaf, aku tidak tahu jawaban dari pertanyaanmu
orang-orang memanggil saya GLaDOS
hari ini tanggal 18
